# Github Action for Python Virtual Environments
name: 'Python venv setup'
description: 'Configures python virtual environment and runs additonal steps'
inputs: 
  python-version:
    description: 'Python version, default is 3.8'
    required: true
  requirements-file:
    description: 'Path to requirements file'
    required: true
  constraints-file:
    description: 'Path to requirement constraints file'
    required: true
  constraints:
    description: 'Constraints on inidividual package versions'
    required: true
  run:
    description: 'Takes the shell commands as input and runs them in a shell with the virtual environment activated'
    required: true
  venv-dir:
    description: 'Path to venv'
    required: false
    default: '.venv'
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Create Virtual Environment
      id: create-venv
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
      run: python -m venv ${{ inputs.venv-dir }}
      shell: bash
    - name: Install requirements
      run: |
        python -m pip install -r ${{ inputs.requirements-file }}
        python -m pip install ${{ inputs.requirements }}
      shell: bash
    - name: Install Constraints
      run: |
        python -m pip install -c ${{ inputs.constraints-file }}
        python -m pip install ${{ inputs.constraints }}
      shell: bash
    - name: Run additional shell commands in venv
      run: |
        source .venv/bin/activate
        ${{ inputs.run }}
      shell: bash
